### ISSUE TITLE
set new object

### ISSUE THREAD

**Issue by ctxhou** [zordius/json-path-processor#3]
Hi,

In your README, you show a `set` example like this.

		
	// will get {a: {b: 'OK', c:[1, 4]}}
	console.log(jpp({a: {b: 'OK', c: [1, 4]}}).set('a.b.c.d', 'OK?').value());
	
So it means that this package didn't support add a new key value?

like
	
	jpp({a: {b: 'OK'}}).set('a.c', 'OK?')
	=> {a: {b: 'OK', c: 'OK'}}

**Comment by zordius** [comment]
by default, it will not create new key. But, you can use 3rd param to enable 'create' feature.

```
// will get {a: {b: 'OK', c:[1, 4], d: 'OK?'}}
console.log(jpp({a: {b: 'OK', c: [1, 4]}}).set('a.b.d', 'OK?', true).value());

// supported by this way
jpp({a: {b: 'OK'}}).set('a.c', 'OK?', true)
=> {a: {b: 'OK', c: 'OK?'}}
```

**Comment by ctxhou** [comment]
ok thanks!
