### ISSUE TITLE
I'm having an issue creating properties that have a '.' in them

### ISSUE THREAD

**Issue by ericuldall** [zordius/json-path-processor#5]
Is there a way to place a . as part of the property name for instance:

    jpp({}).set('internet.sites.[google.com], true)

__good result__:

    {internet: {sites:{"google.com": true}}}

__bad result:__

    {internet:{sites:{google:{com: true}}}}

**Comment by zordius** [comment]
a better way to deal with this is following the JSONPath spec: http://goessner.net/articles/JsonPath/ ,
it should be something like `internet.sites.['google.com']` , when it's a single quoted string it should be `'internet.sites.[\'google.com\']'` . We should do some enhancement to support this.

**Comment by facetothefate** [comment]
it seems like we need a grammar analyzer.

Zordius <notifications@github.com>于2015年7月22日周三 22:16写道：

**Comment by ericuldall** [comment]
how do  you deal with this scenario?

   'internet.sites.special_key[mykeyactuallyhasbracketsforsomereason][google.com]'
   //should yield
   {internet: {sites: {"special_key[mykeyactuallyhasbracketsforsomereason]": {"google.com": val}}}}

**Comment by zordius** [comment]
The JsonPath rules just follow the JavaScript array or object property syntax, which is:

```javascript
foo.bar.tee == foo['bar']['tee'] == foo.bar['tee'] == foo['bar'].tee == foo["bar"]["tee"] ;   // true
```

When you express a property with the array syntax, then you can put any character into the string with `\` to escape it. This rule is same with JavaScript code, so it is good to follow it.

**Comment by zordius** [comment]
New version v0.2.3 released and support array syntax now, please read the new document https://github.com/zordius/json-path-processor#supported-json-path , thanks!

**Comment by ericuldall** [comment]
Is this available on npm yet?
